### PR TITLE
Blecki dev

### PR DESCRIPTION
**Pull request by Blecki**
Slow progress. Good idea to merge since this change touched so many files.

### CODE REVIEW

**Comment by mklingen** [comment]
Must fix #73 and #72  before merging.

**Comment by Blecki** [comment]
Are you handling 72?

**Comment by mklingen** [comment]
I can fix #72 Friday night when I have time. It looks like the only thing that was affected was WorldManager.cs, and just a few lines.

**Comment by mklingen** [comment]
Okay I fixed #72. I will now

**Pull request merged**
